### ISSUE TITLE
Debug is always True and there is no logging

### ISSUE THREAD

**Issue by macwilam** [dagnelies/canister#1]
Hi,
I am not sure if this issue is with cannister or somewhere else Bu i thought I will post here first.
Even when I set debug to False everywhere possible in the line 79 in the expression is always evaluated as true.
79: if debug:
Therefore I was unable to get any file logging started.
Truly no matter what I do.  What is funny is that the logger streams to console that debug is False. 
Am I doing something wrong?
Obvioulsy when I change the line 79 to
if False:
then all my logging works as intended.
PS Thanks for this module it makes life easier :) 

EDIT:
I did some testing. It looks as if the reason is that I didn't understand how I should name my keys.
config.get('canister.debug', True)
if i change it to:
config.get('debug', True) 
Therefore the keys should have conf. prefix.

Sorry for missing this and starting the issue.

**Comment by dagnelies** [comment]
Hi,

have you tried it like the example?

```python
import bottle
import canister
from canister import session

app = bottle.Bottle()
app.config.load_config('<my-config-file-path>')
app.install(canister.Canister())
...
```

and in the `<my-config-file-path>` config file:

```
[canister]
debug = False
# The logs directory
log_path = ./logs/
# Logging levels: DISABLED, DEBUG, INFO, WARNING, ERROR, CRITICAL
log_level = INFO
# Log older than that will be deleted
log_days = 30
#...
```

**Comment by macwilam** [comment]
I wanted to change just one parameter at first so I didn't try the configuration through the config file.
It is totally my bad :)
This issue should be closed.

**Comment by dagnelies** [comment]
The `load_config('<my-config-file-path>')` line was missing in the readme example, it's understandable.
