### ISSUE TITLE
Multiple credentials for basic authentication?

### ISSUE THREAD

**Issue by melissaboiko** [dagnelies/canister#10]
It would be cool if the module supported basic authentication for multiple users, rather than a single one (perhaps reading a password file in Apache htpasswd format).

**Comment by dagnelies** [comment]
Well, this is opening a can of worms. The first will store it in a password file, the other in mysql, the other wants a custom method, the other wants a specific route only...

Moreover, there are two really simple ways to achieve this already:
1. use `@bottle.auth_basic(checkUserPasswordFunction)` on the restricted routes
2. use OAuth2 (with a service like https://auth0.com/ for example, you'll just have to fill the three parameters in the config)

**Comment by melissaboiko** [comment]
Oh damn, somehow I missed the fact that bottle already had an `auth_basic` feature.  (External services aren't adequate for our use case.) I ended up going with Cork anyway, despite its disagreeable verbosity.  Thanks for the reply!
