### ISSUE TITLE
Canister separated session data for different session-IDs

### ISSUE THREAD

**Issue by ghost** [dagnelies/canister#12]
I have copied your suggested session code and tried to run it from different browsers.  A different session-ID is assigned to the different sessions, but the session data, i.e. the counter, is shared among them.  More specifically, if I click three times in one browser, the counter data in that browser is '3'.  If I then switch to a different browser, a different session-ID is assigned.  But if I open the site the browser is set to '4'.  If I click three times, the counter data is '6'.  If I open yet another browser, the same thing happens, a different session-ID is assigned but the counter data keeps counting up from the last value in the previous browser.  

I expected that the counter data would be independent in the different browsers.  

If my expectations are out of line, or I'm doing something wrong, please let me know, and some direction would be much appreciated.  

Thanks,

Den

**Comment by ghost** [comment]
I think I found a (the?) problem.  I downloaded the latest version from here and compared it to the version from pypi.  There were a couple of differences in the session_cache class, and when I use this version it works the way I expect it to.

**Comment by dagnelies** [comment]
This issue seem familiar. It was indeed fixed long ago but not released on pypi because of #7.

A couple of years ago, the pypi repo and how packages were submitted changed. Their whole website and backend were replaced, making me unable to easely publish releases anymore. I might give it another shot.

**Comment by dagnelies** [comment]
#7 was solved, yay! 🎉 

The new release is now available on pip! ;)
