### ISSUE TITLE
Terminate a session

### ISSUE THREAD

**Issue by ghost** [dagnelies/canister#13]
I have programmed a relatively simple server using bottle and canister.  I have a need to terminate a session (but not the server or other session) due to server error or client request.  I have reviewed the docs and this is not covered there.  I've reviewed the source code, but I'm afraid it's a bit above me.  

Is there a way to terminate a session?  If not, can such a function be added.

Thanks.

**Comment by dagnelies** [comment]
Hmmm... it's quite some time I made that code.

There is no built-in way to kill sessions.

Basically, there are two parts of it:

1. the browser has a `session_id` cookie which should be deleted (to be done using the HTTP response)
2. the server side has data belonging to `session_id` which should be deleted (it will be anyway after some timeout occurs)

So, basically, either of these actions would invalidate the session. However, it would be definitely cleaner to do both.

For 1. I think you can use something like: `bottle.response.del_cookie('session_id')` ...or if bottle has no such method, with a HTTP Header directly

For 2. I think you can use: `canister.sessions.delete(session.sid)`

...I don't really have time to work on this right now, but it would be very welcome if you submit a pull request once you resolved this to put it in a nice little function like `session.terminate/kill/delete()`
```

**Comment by dagnelies** [comment]
@dncarac Did that help?

**Comment by ghost** [comment]
@dagnelies I tried it, but they come back with variables undefined.  I'm going to start looking at your code to see if I can figure it out.  Thanks for your post.

**Comment by dagnelies** [comment]
undefined? ...well, sounds like it is gone then. :)

After deleting the session that way, a new empty one will be created with the next HTTP request. Alternatively, you could simply remove/reset/clear the session variables, voiding the need to kill the session and create a new one.

**Comment by ghost** [comment]
Ahhh.   Deleting the session variables is a lot easier.  Let me try that.  I was afraid if I just `del session` it might upset some internal structure.  I am working on it, though
