### ISSUE TITLE
Session persistence

### ISSUE THREAD

**Issue by georgy7** [dagnelies/canister#16]
**Motivation:** to avoid disturbing users during deployment.

**Proposed way:** to load sessions from disk when an application starts, because this way you don't need to read the disk at every HTTP request.

I wonder if this approach is correct, in your opinion.

```python
import canister
import bottle


app = bottle.Bottle()
app.config.load_config('app.ini')
app.install(canister.Canister())


for plugin in app.plugins:
    if isinstance(plugin, canister.Canister):
        for sid, username, data in read_from_disk_or_db():
            plugin.sessions.set(sid, username, data)


# Methods that process HTTP requests...
```

**Comment by dagnelies** [comment]
Sessions are not persisted in the first place. They are kept in memory. Redeploying your application would clear existing sessions.

**Comment by dagnelies** [comment]
It's even the first line after the "Sessions" title in the [README](https://github.com/dagnelies/canister#sessions)

> Sessions are kept server side in memory

**Comment by georgy7** [comment]
I know, I've read the documentation and the code. I was asking for your opinion...
