### ISSUE TITLE
Python2 threading error

### ISSUE THREAD

**Issue by Phyks** [dagnelies/canister#2]
Hi,

`threading.Thread` does not have a `daemon` keyword argument in Python 2.7 apparently, which leads to this error when using `canister`:

```
[...]
    cleaner = threading.Thread(name="SessionCleaner", target=prune, daemon=True)
TypeError: __init__() got an unexpected keyword argument 'daemon'
```

This looks similar to https://github.com/dask/distributed/issues/18. 

As the [`daemon` property is set afterwards](https://github.com/dagnelies/canister/blob/master/canister.py#L172), I guess the `daemon` keyword argument could simply be removed from [this line](https://github.com/dagnelies/canister/blob/master/canister.py#L171) which would solve the issue.

Thanks!

**Comment by dagnelies** [comment]
Done :)

TODO: test, bump version and push to pip... :/

**Comment by Phyks** [comment]
Awesome, thanks! Looking forward to having it landed in pip :)

**Comment by dagnelies** [comment]
done

**Comment by Phyks** [comment]
Awesome! :)
