### ISSUE TITLE
Issue with getargspec and functools partial

### ISSUE THREAD

**Issue by Phyks** [dagnelies/canister#3]
Hi,

There is an issue with the use of `inspect.getargspec` for [args unpacking](https://github.com/dagnelies/canister/blob/master/canister.py#L311).

Typically, some Bottle plugins replace keyword arguments in routes (to automatically inject a database session in routes having a `db` argument for instance). This may be done through a partial application of the route method.

I think some implementation like [this one](https://github.com/ipython/traitlets/blob/master/traitlets/utils/getargspec.py) would be better.

Thanks

**Comment by dagnelies** [comment]
thanks for the suggestion. However, I'm not convinced to invest time in it:

1. it *adds complexity* (some args come from requests, other from plugins, depends on the order...)
2. applying the function completely has also the *purpose of checking missing arguments*
3. it has *simple workaround*: you could simply use `db=None` as arg so that it would be overwritten by your plugin

If you think it's important, you're welcome to submit a PR though (including a test too).

**Comment by Phyks** [comment]
Simple workaround would be to actually return a wrapper route rather than a partial application, I agree. I did not get your point with `db=None`.

I would tend to think using `functools` module and partial evaluation is cleaner and closer to functional programming for this kind of behavior (dependency injection), so I would prefer it over a wrapper.

Typical example is [bottle-sqlalchemy](https://github.com/iurisilvio/bottle-sqlalchemy) (except that this one returns a wrapper and not a partial application).

**Comment by dagnelies** [comment]
>  I did not get your point with db=None.`

Well, if you register both the `canister` plugin, then your `db-wrapper` plugin, won't the second simply overwrite the `db` arg? The `db=None` was just intended to avoid a "Missing arg" exception from canister.

**Comment by Phyks** [comment]
Oh, indeed, I was not aware that the order of plugins was important with `bottle`, my bad.

So, the simplest workaround is to simply do:

```python
    app = bottle.default_app()
    app.install(DatabasePlugin(get_session))
    app.install(canister.Canister())
```

and everything works like a charm! Thanks a lot, and sorry for the noise :/
