### ISSUE TITLE
Useless import

### ISSUE THREAD

**Issue by Phyks** [dagnelies/canister#5]
Hi,

Isn't https://github.com/dagnelies/canister/blob/master/canister.py#L18 a useless import?

If it is useless, would it be possible to remove it?

Else, this module is not part of `stdlib` in Python 2 (it is called `ConfigParser` actually). For anyone having issues with it, they should either install [this backport](https://github.com/bottlepy/bottle/blob/41ed6965de9bf7d0060ffd8245bf65ceb616e26b/bottle.py#L121-L154) or handle it differently across Py2 and Py3, as [Bottle do](https://github.com/bottlepy/bottle/blob/41ed6965de9bf7d0060ffd8245bf65ceb616e26b/bottle.py#L121-L154). Mainly posting it here in case anyone has this issue and google it (if the module is actually needed, I would consider it to be ok to keep it as is).

Thanks!

**Comment by dagnelies** [comment]
Done 👍

**Comment by Phyks** [comment]
You are so reactive, that's impressive! That's awesome, thanks a lot!
